### ISSUE TITLE
초기 개발용 mongodb 연결을 위한 application.yml 세팅

### ISSUE THREAD

**Issue by Oodls** [itcen-project-2team/sketch-quiz-server#1]
### run-mongodb.sh (저장소에 있음)
```
#!/bin/bash

# 개발용 MongoDB 컨테이너 최초 생성 스크립트
# 한번 이 명령 실행 한 후에는 docker mongodb start 로 실행 가능

docker run -d \
  --name mongodb \
  -p 27017:27017 \
  -e MONGO_INITDB_ROOT_USERNAME=root \
  -e MONGO_INITDB_ROOT_PASSWORD=root \
  mongo
```

### application.yml (.gitignore 설정 되어 있어 직접 입력)
```
spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/whiteboard?authSource=admin

```
